# define the cpu used by the saml21 board
export CPU = saml21
export CPU_MODEL = saml21e18b
export CFLAGS += -D__SAML21E18B__

# set edbg device type
EDBG_DEVICE_TYPE = atmel_cm0p

include $(RIOTMAKE)/boards/sam0.inc.mk
